Neos:
  Neos:
    fusion:
      autoInclude:
        Garagist.ImageDirectory: true
    userInterface:
      translation:
        autoInclude:
          Garagist.ImageDirectory:
            - 'NodeTypes/*'
