Neos:
  Neos:
    fusion:
      autoInclude:
        Garagist.ImageDirectory: true
    userInterface:
      translation:
        autoInclude:
          Garagist.ImageDirectory:
            - 'NodeTypes/*'

Garagist:
  ImageDirectory:
    # List of filenames who should be always ignored. Case-insensitive.
    ignoreFilenames:
      'favicon.ico': true
      'favicon.png': true
      'apple-touch-icon.png': true
